// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFrXIMyMkStx8vNONcMksZsmdxgQULVWo',
    appId: '1:356670522282:web:74417eef20d07b8cce61d3',
    messagingSenderId: '356670522282',
    projectId: 'ferolino-chat-app',
    authDomain: 'ferolino-chat-app.firebaseapp.com',
    storageBucket: 'ferolino-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs0qbxx8TPn3ww89uORq-AXqUMEJLYFOA',
    appId: '1:356670522282:android:cf75dee179eeb9d1ce61d3',
    messagingSenderId: '356670522282',
    projectId: 'ferolino-chat-app',
    storageBucket: 'ferolino-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1q_rkmKCKIJ5J3U1hv2A0cTgm_PmkHVk',
    appId: '1:356670522282:ios:7bc46d159d7fbebfce61d3',
    messagingSenderId: '356670522282',
    projectId: 'ferolino-chat-app',
    storageBucket: 'ferolino-chat-app.appspot.com',
    iosClientId: '356670522282-s3o4pg85iunq0b35q36cjjmkbnnjn6k6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
